version: '3.0'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: zelen-app
    ports:
     - 5432:5432
  
  $PROJECT:
    image: $PROJECT:$VERSION
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: zelen.electrostal.space
      LETSENCRYPT_HOST: zelen.electrostal.space
      LETSENCRYPT_EMAIL: gdkharit@electrostal.space
