
CREATE SEQUENCE user_id_sequence INCREMENT 1 START 1000 CACHE 10 OWNED BY USERS.ID
CREATE SEQUENCE operation_id_sequence INCREMENT 1 START 15000 CACHE 10 OWNED BY USERS.ID
CREATE SEQUENCE internal_ops_id_sequence INCREMENT 1 START 25000 CACHE 10 OWNED BY USERS.ID

CREATE TABLE IF NOT EXISTS USERS (
	ID 		  bigint NOT NULL DEFAULT nextval('user_id_sequence'::regclass),
	USERNAME  varchar(200) NOT NULL UNIQUE ,
    PASSWORD  varchar(250) NOT NULL,
	LAST_SEEN bigint NOT NULL,
	USER_ROLE	  smallint NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USER_INFO (
	USER_ID       bigint NOT NULL,
	FIRST_NAME    varchar(100) NOT NULL,
    LAST_NAME    varchar(100) NOT NULL,
	BIRTH_DATE	  date NOT NULL,
	EMAIL		  varchar(100) NOT NULL,
    ADDRES_COUNTRY	varchar(150) DEFAULT NULL,
    ADDRES_CITY	varchar(150) DEFAULT NULL,
	PRIMARY KEY(USER_ID),
	FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS USER_BALANCE (
	USER_ID bigint NOT NULL,
	BALANCE real,
 	PRIMARY KEY(USER_ID),
	FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS USER_PREFERENCES (
	USER_ID bigint NOT NULL,
	TIME_SHIFT varchar (20) default 'UTC',
	PRIVACY smallint DEFAULT 0,
 	PRIMARY KEY(USER_ID),
	FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS USER_OPERATIONS (
	ID 	bigint NOT NULL DEFAULT nextval('operation_id_sequence'::regclass),
	FIRST_USER_ID       bigint NOT NULL,
	SECOND_USER_ID       bigint NOT NULL,
	OP_TYPE	smallint NOT NULL,
    INCOME real NOT NULL,
	OUTCOME	real NOT NULL,
	FEE 	real NOT NULL,
	created bigint NOT NULL,
	updated bigint NOT NULL,
	OP_STATE smallint NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(FIRST_USER_ID) REFERENCES USERS(ID)
	FOREIGN KEY(SECOND_USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS ADMIN_OPERATIONS (
	ID 	bigint NOT NULL DEFAULT nextval('internal_ops_id_sequence'::regclass),
	USER_ID       bigint NOT NULL,
	ADMIN_ID       bigint NOT NULL,
	OP_TYPE	smallint NOT NULL
	created bigint NOT NULL,
	reason  text NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
	FOREIGN KEY(ADMIN_ID) REFERENCES USERS(ID)
);



